doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
          # server: '%env(resolve:MONGODB_URL)%'
            server: "%mongodb_server%"
            options: {}
    #default_database: '%env(resolve:MONGODB_DB)%'
    default_database: 'test'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
