#index:
#    path: /
#    controller: App\Controller\DefaultController::index


testformbdd:
    path: /bdd
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\testv2::formbdd    
    
routesubmitsuccess:
    path: /action
    controller: App\Controller\testv2::action 